services:
  - type: web
    name: voora-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGO_URI
        sync: false
      - key: PORT
        value: 5000
      - key: CLIENT_URL
        sync: false
